# **Module 1: Basic**

Variable

In [ ]:
#variable
a = 10
print(a)
print(type(a))

10
<class 'int'>

In [ ]:
b = 1.2
print(type(b))

<class 'float'>

In [ ]:
a = b
print(type(a))

<class 'float'>

In [ ]:
name = "sadman"
print(type(name))

<class 'str'>

In [ ]:
data = input()
print(data)
print(type(data))

12
12
<class 'str'>

In [ ]:
a = input()
a = int(a)
print(a)
print(type(a))

12
12
<class 'int'>

In [ ]:
row_number = input()
numbers = row_number.split()

a = int(numbers[0])
print(a)
print(type(a))

b = int(numbers[1])
print(b)
print(type(b))

print(a+b)

12 12
12
<class 'int'>
12
<class 'int'>
24

Condition

In [ ]:
import torch
import torch.nn as nn

image_features = torch.tensor([[0.15, 0.85, 0.25, 0.70]])

model = nn.Sequential(
    nn.Linear(4,12),
    nn.ReLU(),
    nn.Linear(12,1),
    nn.Sigmoid()
)


with torch.no_grad():
    prediction = model(image_features)

prob = prediction.item()
print(f"Probability of being a Dog: {prob:.4f}")


if prob == 0.5:
   print("Couldn't classify the image")

elif prob > 0.5:
  print("Dog")
else:
  print("Cat")

Probability of being a Dog: 0.5427
Dog

LOOP

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

data = load_breast_cancer()
X, y = data.data, data.target


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

k_values = range(1, 51)
accuracies = []

print(f"{'K Value'} | {'Test Accuracy'}")


for k in k_values:
    # Initialize and fit
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    # Calculate accuracy
    score = knn.score(X_test, y_test)
    accuracies.append(score)


print(accuracies)

print(len(accuracies))


mx_accuracy = max(accuracies)

print(mx_accuracy)

best_k_index = accuracies.index(mx_accuracy)

best_k = k_values[best_k_index]


print(best_k)

K Value | Test Accuracy
[0.935672514619883, 0.9298245614035088, 0.9415204678362573, 0.9473684210526315, 0.9590643274853801, 0.9590643274853801, 0.9649122807017544, 0.9649122807017544, 0.9707602339181286, 0.9824561403508771, 0.9766081871345029, 0.9766081871345029, 0.9649122807017544, 0.9649122807017544, 0.9649122807017544, 0.9649122807017544, 0.9649122807017544, 0.9649122807017544, 0.9590643274853801, 0.9649122807017544, 0.9532163742690059, 0.9532163742690059, 0.9532163742690059, 0.9532163742690059, 0.9473684210526315, 0.9532163742690059, 0.9473684210526315, 0.9532163742690059, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.935672514619883, 0.9473684210526315, 0.9415204678362573, 0.9415204678362573, 0.9415204678362573, 0.9415204678362573, 0.9415204678362573, 0.9473684210526315, 0.9415204678362573, 0.9415204678362573, 0.935672514619883, 0.9415204678362573, 0.935672514619883, 0.935672514619883, 0.935672514619883, 0.9415204678362573, 0.935672514619883, 0.9473684210526315]
50
0.9824561403508771
10

Dictionary

In [ ]:
#dictionary

model_configs = {
    "KNN":{
      "model": KNeighborsClassifier,
      "params": [3,5,11]
    },
    "Random Forest":{
      "model": RandomForestClassifier,
      "params": [10,50,100]
    },
}

In [ ]:
import pandas as pd

ml_results = {
    "Model_Name":["KNN","RandomForest","LogisticReg"],
    "Best_K": [5,100,None],
    "Accuracy": [0.942,0.965,0.910],
    "Train_Time_Sec": [0.02,1.45,0.08]
}

df = pd.DataFrame(ml_results)
df.head()

     Model_Name  Best_K  Accuracy  Train_Time_Sec
0           KNN     5.0     0.942            0.02
1  RandomForest   100.0     0.965            1.45
2   LogisticReg     NaN     0.910            0.08

# **Module 2: Function**

In [ ]:
def welcome_message():
  print("hello user")

In [ ]:
welcome_message()

hello user

In [ ]:
def welcome_message(user="None"):
  print(f"hello {user}")

In [ ]:
welcome_message("sadman")
welcome_message()

hello sadman
hello None

In [3]:
def adder(a,b):

  """ # this is docstring
  add two numbers
  a-> int
  b-> int
  return sum = a+b -> int
  """
  sum = a+b
  return sum

In [7]:
adder (10,30)*5
help(adder)

Help on function adder in module __main__:

adder(a, b)
    add two numbers
    a-> int
    b-> int
    return sum = a+b -> int

In [12]:
#positional argument

def adder2(a,b,c,d,e,f):
  return a+b+c+d+e+f

#variable size argument
def unlimited_argument(*args):
  for i in args:
    print(i)

In [11]:
unlimited_argument(1,2,3,4,5,6,7,8,9,10)

1
2
3
4
5
6
7
8
9
10

In [18]:
def adder(a,b,c):
  print(f'a = {a}')
  print(f'b = {b}')
  print(f'c = {c}')

In [15]:
adder(a = 10,c=20,b = 30)

a = 10
b = 30
c = 20

In [21]:
#keyword argument
def adder(**kwargs):
  for key,value in kwargs.items():
    print(f"key: {key} value: {value}")


adder(a = 10, b = 30,c = 40, n_estimator = 50)

key: a value: 10
key: b value: 30
key: c value: 40
key: n_estimator value: 50

In [25]:
def adder(a,b):
  return a,b
#unzip

x,y = adder(10,20)
print(adder(20,30)) #tuple
print(x,y)

(20, 30)
10 20

In [40]:
#iterator
data_set = {10,20,30,40,50}
# print(data_set[0]) -> error dibe

s_iter = iter(data_set)
print(s_iter)
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))


dict_data = {
    "data1": {
        "list":[1,2,3,4,5],
        "tuple":(1,2,3,4,5),
        "set":{1,2,3}
    },
    "data2":{
        "list":[10,20,30,40,50],
        "tuple":(10,20,30,40,50),
        "set":{10,20,30}
    }
}

d_iter = iter(dict_data)
print(d_iter)
print(next(d_iter))

<set_iterator object at 0x7eac9b3c9bc0>
50
20
40
10
30
<dict_keyiterator object at 0x7eac9b3c1d50>
data1

In [47]:
#generator
lst = [x for x in range(500)] #data
def data_loader(chunk_size,lst):
  for i in range(0,len(lst),chunk_size):
    yield lst[i: i+chunk_size]


x = data_loader(10,lst)
print(type(x))
print(x)
print(next(x))
print(next(x))
print(next(x))
print(next(x))

<class 'generator'>
<generator object data_loader at 0x7eac9b42a7a0>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]

In [52]:
import pandas as pd

df = pd.DataFrame({"A": [1,2,3,4,5],"B":[6,7,8,9,10]})
df

# df["A"] = df["A"].map(lambda x: x**0.5)
# df
df["A"] = df["A"].apply(lambda x: x**0.5)
df

          A   B
0  1.000000   6
1  1.414214   7
2  1.732051   8
3  2.000000   9
4  2.236068  10

In [55]:
df = pd.DataFrame({"total_spent": [10,20,30,40,50]})

df
df["high_spend"] = df["total_spent"].apply(lambda x: 1 if x> 21 else 0 )
df

   total_spent  high_spend
0           10           0
1           20           0
2           30           1
3           40           1
4           50           1